title: Tim's corner
email: timosahenru@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/mycorner"
url: "https://timosahenru.github.io"
twitter_username: _osahenru
github_username:  timosahenru

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# permalink: "/:path/"

paginate: 6
paginate_path: "/notes/page:num/"